### ISSUE TITLE
lacross bridge

### ISSUE THREAD

**Issue by Jayhawk85** [matthewwall/weewx-interceptor#3]
When I try to use the lacross-bridge switch, the driver install fails with unsupported driver type

**Comment by matthewwall** [comment]
in weewx.conf, change to 'lacrosse-bridge' instead of 'lacross-bridge':

device_type = lacrosse-bridge

i must warn you, the driver will probabaly fail even after that.  i do not have lacrosse hardware on which to test.  would you be willing to provide me with remote access to the computer running weewx so i can get everything to work?

**Comment by Jayhawk85** [comment]
actually, just tried that and it loaded (at least according to syslog)  Just a typo in the notes

**Comment by Jayhawk85** [comment]
Sure (trying to figure out how we would do that).

**Comment by matthewwall** [comment]
- make a user account for mwall:

sudo adduser mwall

- be sure sshd is installed and running

- make port 22 accessible to the internet by mapping some port on your router's WAN interface to port 22 on the computer running weewx

**Comment by Jayhawk85** [comment]
open.  give me an email to send the pw to  ip is 67.217.9.126

**Comment by matthewwall** [comment]
mwall@users.sourceforge.net

**Comment by Jayhawk85** [comment]
on the way

**Comment by Jayhawk85** [comment]
were you able to get in?

**Comment by matthewwall** [comment]
continuing the conversation in email

**Comment by matthewwall** [comment]
as of commit e4a4b74 the driver is working with lacrosse GW1000U for the current observations
