### ISSUE TITLE
Multiple channels and UV index with LW301

### ISSUE THREAD

**Issue by ratava** [matthewwall/weewx-interceptor#7]
Hi Matt

First of all. Great job on the driver. I was about to start doing an Arduino setup when I came across this setup to work around the limitation of the Oregon Scientific system.

I have managed to get it working with DNS redirection to my weewx server but I have encountered some problems.

In your code there is no provision for multiple temp sensors on different channels. I have done a workaround on this by examining the channel number in the loop and then telling it to the map_fields routine when it can assign a different sensor map based on the channel number. I use this for inTemp, inHumidity and outTemp and outHumidity.  I am happy to send you my code if you want, I am not much of a python programmer so it's a bit rough but it might help you change the base so others can use it.

Secondly The UV value from the 8e packet is being read wrong. You are taking the uv value which gives you something like, 290 or 154. I am not sure why the sensor is sending that but the real value that should be logged is the previous one, uvh. I have checked it's value as being the uv index as displayed on the WMR88 base station. 

The only problem I struck is in the pattern match, it returns a string not a float which is required by the engine.py. A quick check of the key on the parser to convert it to a float fixed that.

I have heaps of packet logs from all of the main sensor types is you want them for testing. 

Thanks for all of your hard work
Brent Wesley.

**Comment by matthewwall** [comment]
brent,

thank you for the feedback.

for multiple sensors (of any type), then idea is to use the sensor_map to map sensors to database fields.  that way no modifications to the code are necessary.  for example,

```
[Interceptor]
    driver = user.interceptor
    [[sensor_map]]
        inTemp = ot.1:*.*
        outTemp = ot:2:*.*
        extraTemp1 = ot.3:*.*
        extraTemp2 = ot.4:*.*
```

this would ignore the rid of each sensor, but distinguishes on the channel.

the sensor id patter is <observation>.<channel>:<rid>.<mac>

the colon was just added at commit 4b740d2

i modified the default sensor map to use uvh instead of uv.  do you know what the range of values is for uvh?

do any of your packet captures help to identify the unknown parameters?
